sudo: required
language: node_js
services:
  - docker
node_js:
  - "9"
install:
  - npm install
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xstoudi/es-bot